{
  "bachelierOutputRootDirectory": "Users/hmaupard/Documents/Personal/Data/Bachelier", # "F:\\financialData\\",
  "assetsPath": "Assets",
  "extradayPricesPath": "HistoricalExtradayPrices",
  "intradayPricesPath": "HistoricalIntradayPrices",
  "logsPath": "Logs"
}
