{
  "bachelierOutputRootDirectory": "/Users/hmaupard/Documents/Personal/Data/Bachelier/",
  "assetsPath": "Assets",
  "extradayPricesPath": "HistoricalExtradayPrices",
  "intradayPricesPath": "HistoricalIntradayPrices",
  "logsPath": "Logs",
  "environmentPythonPath":"/Users/hmaupard/Documents/Personal/python-projects"
}
