{
  "bachelierOutputRootDirectory": "F:\\financialData\\",
  "assetsPath": "Assets",
  "extradayPricesPath": "HistoricalExtradayPrices",
  "intradayPricesPath": "HistoricalIntradayPrices",
  "logsPath": "Logs"
}
